// <auto-generated />
using System;
using M1_PANGAN.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace M1_PANGAN.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250922120945_ConfigureLogFkCascade")]
    partial class ConfigureLogFkCascade
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("M1_PANGAN.Models.Item", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Brand")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<decimal>("UnitPrice")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.ToTable("Items");
            });

            modelBuilder.Entity("M1_PANGAN.Models.LogEntry", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("AfterJson")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("BeforeJson")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int?>("ItemId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("TimestampUtc")
                    .HasColumnType("TEXT");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ItemId");

                b.ToTable("Logs");
            });

            modelBuilder.Entity("M1_PANGAN.Models.LogEntry", b =>
            {
                b.HasOne("M1_PANGAN.Models.Item", null)
                    .WithMany()
                    .HasForeignKey("ItemId")
                    .OnDelete(DeleteBehavior.Cascade);
            });
#pragma warning restore 612, 618
        }
    }
}
